--6DAYS DB

-- 일자 : 2020.02.12 
-- 이름 : 신굥섭
-- 내용 : 공지사항 게시판 
CREATE TABLE BOARD (
   BNO NUMBER PRIMARY KEY, -- 글번호
   BTITLE VARCHAR2(500) NOT NULL, -- 제목
   BCONTENT VARCHAR2(3000) NOT NULL, -- 내용
   BWRITER VARCHAR2(30) NOT NULL, -- 작성자
   BCOUNT NUMBER DEFAULT 0, -- 조회수
   BOARDFILE VARCHAR2(500), -- 첨부파일
   BDATE DATE DEFAULT SYSDATE, -- 작성일
   STATUS VARCHAR2(1) DEFAULT 'N' CHECK (STATUS IN ('N','Y')) -- 삭제여부
   );

COMMENT ON COLUMN BOARD.BNO IS '글번호';
COMMENT ON COLUMN BOARD.BTITLE IS '제목';
COMMENT ON COLUMN BOARD.BCONTENT IS '내용';
COMMENT ON COLUMN BOARD.BWRITER IS '작성자';
COMMENT ON COLUMN BOARD.BCOUNT IS '조회수';
COMMENT ON COLUMN BOARD.BOARDFILE IS '첨부파일';
COMMENT ON COLUMN BOARD.BDATE IS '작성일';
COMMENT ON COLUMN BOARD.STATUS IS '삭제여부';


-- 일자 : 2020.02.12 
-- 이름 : 윤사쿤
-- 내용 : 사용자 

CREATE TABLE USERMEMBER (
      USERID VARCHAR2(100) PRIMARY KEY,  --유저 아이디
      USERPWD VARCHAR2(100) NOT NULL,  --유저 비밀번호
      USERNAME VARCHAR2(100) NOT NULL,  --유저 닉네임
      EMAIL VARCHAR2(100), --이메일
      PHONE VARCHAR2(14), --휴대폰번호
      GENDER CHAR(1) CHECK (GENDER IN ('M', 'F')), --성별
      MYCOMMENT VARCHAR2(100), --소개글
      PROIMG VARCHAR2(200), --프로필 이미지
      PROBACK VARCHAR2(200), --프로필 배경
      ENROLLDATE DATE DEFAULT SYSDATE, --시작일
      OTYPE CHAR(1) CHECK(OTYPE IN ('1','2','3')), --공개여부           //전체공개, 비공개, 친구만공개 
      ADMIN_YN CHAR(1) CHECK(ADMIN_YN IN ('Y','N')), --권한여부
      BLOCKFLAG CHAR(1) CHECK(BLOCKFLAG IN ('Y','N')), --정지유무
      REPORT_YN CHAR(1) CHECK(REPORT_YN IN ('Y','N')),--신고유무
      DELFLAG CHAR(1) CHECK (DELFLAG IN ('Y','N')) --삭제여부
      
); 

COMMENT ON COLUMN USERMEMBER.USERID IS '아이디';
COMMENT ON COLUMN USERMEMBER.USERPWD IS '비밀번호';
COMMENT ON COLUMN USERMEMBER.USERNAME IS '닉네임';
COMMENT ON COLUMN USERMEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN USERMEMBER.PHONE IS '휴대폰번호';
COMMENT ON COLUMN USERMEMBER.GENDER IS '성별';
COMMENT ON COLUMN USERMEMBER.MYCOMMENT IS '소개글';
COMMENT ON COLUMN USERMEMBER.PROIMG IS '프로필 이미지';
COMMENT ON COLUMN USERMEMBER.PROBACK IS '프로필 배경';
COMMENT ON COLUMN USERMEMBER.ENROLLDATE IS '시작일';
COMMENT ON COLUMN USERMEMBER.OTYPE IS '공개여부';
COMMENT ON COLUMN USERMEMBER.ADMIN_YN IS '권한여부';
COMMENT ON COLUMN USERMEMBER.BLOCKFLAG IS '정지유무';
COMMENT ON COLUMN USERMEMBER.REPORT_YN IS '신고유무';
COMMENT ON COLUMN USERMEMBER.DELFLAG IS '삭제여부';


-- 일자 : 2020.02.17
-- 이름 : 신경섭
-- 내용 : QNA 게시판 DB
CREATE TABLE QNA (
   QNO NUMBER PRIMARY KEY, -- 글번호
   QTYPE VARCHAR2(10) NOT NULL, -- 구분(공개/비공개)
   QTITLE VARCHAR2(500) NOT NULL, -- 제목
   QCONTENT VARCHAR2(3000) NOT NULL, -- 내용
   QWRITER VARCHAR2(30) NOT NULL, -- 작성자
   QCOUNT NUMBER DEFAULT 0, -- 조회수
   QNAFILE VARCHAR2(500), -- 첨부파일
   QCOMMENT NUMBER DEFAULT 0, -- 댓글수
   QDATE DATE DEFAULT SYSDATE, -- 작성일
   STATUS VARCHAR2(1) DEFAULT 'N' CHECK (STATUS IN ('N','Y')) -- 삭제여부
   );

COMMENT ON COLUMN QNA.QNO IS '글번호';
COMMENT ON COLUMN QNA.QTYPE IS '구분';
COMMENT ON COLUMN QNA.QTITLE IS '제목';
COMMENT ON COLUMN QNA.QCONTENT IS '내용';
COMMENT ON COLUMN QNA.QWRITER IS '작성자';
COMMENT ON COLUMN QNA.QCOUNT IS '조회수';
COMMENT ON COLUMN QNA.QNAFILE IS '첨부파일';
COMMENT ON COLUMN QNA.QCOMMENT IS '첨부파일';
COMMENT ON COLUMN QNA.QDATE IS '작성일';
COMMENT ON COLUMN QNA.STATUS IS '삭제여부';


-- 일자 : 2020.02.18
-- 이름 : 이서현
-- 내용 : (사진 업로드) P_BOARD
CREATE TABLE P_BOARD(

    PBNO NUMBER PRIMARY KEY, --게시판 번호
    PBWRITER VARCHAR2(100) ,  --사진게시판 작성자
    PBDATE DATE DEFAULT SYSDATE, --사진게시판 작성일
    PHOTO1 VARCHAR2(1000),
    PHOTO2 VARCHAR2(1000), --사진들
    PHOTO3 VARCHAR2(1000),
    PHOTO4 VARCHAR2(1000),
    PHOTO5 VARCHAR2(1000),
    PHOTO6 VARCHAR2(1000),
    PCONTENT VARCHAR2(1000), --게시글 내용
    HASHTAG VARCHAR2(500), --해시태그
    LIKE_COUNT NUMBER DEFAULT 0, --좋아요 누른 수 
    PBCOMMENT NUMBER DEFAULT 0, --사진게시판 댓글 수 
    DELFLAG CHAR(1) DEFAULT 'N' CHECK (DELFLAG IN ('Y','N')), --삭제여부 STATUS대신
    BLOCKFLAG CHAR(1) DEFAULT 'N' CHECK(BLOCKFLAG IN ('Y','N')), --정지유무
    REPORT_YN CHAR(1) DEFAULT 'N' CHECK(REPORT_YN IN ('Y','N'))--신고유무
      
    );
    
COMMENT ON COLUMN P_BOARD.PBNO IS '게시판번호';
COMMENT ON COLUMN P_BOARD.PBWRITER IS '작성자';
COMMENT ON COLUMN P_BOARD.PBDATE IS '작성일';
COMMENT ON COLUMN P_BOARD.PHOTO1 IS '사진1';
COMMENT ON COLUMN P_BOARD.PHOTO1 IS '사진2';
COMMENT ON COLUMN P_BOARD.PHOTO1 IS '사진3';
COMMENT ON COLUMN P_BOARD.PHOTO1 IS '사진4';
COMMENT ON COLUMN P_BOARD.PHOTO1 IS '사진5';
COMMENT ON COLUMN P_BOARD.PHOTO1 IS '사진6';
COMMENT ON COLUMN P_BOARD.PCONTENT IS '게시글내용';
COMMENT ON COLUMN P_BOARD.HASHTAG IS '해시태그';
COMMENT ON COLUMN P_BOARD.LIKE_COUNT IS '좋아요누른수';
COMMENT ON COLUMN P_BOARD.PBCOMMENT IS '댓글수';
COMMENT ON COLUMN P_BOARD.DELFLAG IS '삭제여부';
COMMENT ON COLUMN P_BOARD.BLOCKFLAG IS '정지여부';
COMMENT ON COLUMN P_BOARD.REPORT_YN IS '신고유무';



CREATE SEQUENCE SEQ_BNO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;
CREATE SEQUENCE SEQ_CNO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;
CREATE SEQUENCE SEQ_QNO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;
CREATE SEQUENCE SEQ_PBNO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_MNO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;
CREATE SEQUENCE SEQ_PLNO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;


-- 일자 : 2020.02.22
-- 이름 : 신경섭, 윤석훈, 박주완
-- 내용 : 댓글
CREATE TABLE MAINCOMMENT (
    PBNO NUMBER,
    MNO NUMBER PRIMARY KEY,
    MWRITER VARCHAR2(30) NOT NULL,
    MCONTENT VARCHAR2(3000) NOT NULL,
    MNICKNAME VARCHAR2(30) NOT NULL,
    MDATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(1) DEFAULT 'N' CHECK (STATUS IN ('N', 'Y'))
    );
    
    
-- 일자 : 2020.02.23
-- 이름 : 이서현
-- 내용 : 게시물 좋아요 관련
CREATE TABLE PLIKE(
    USERID VARCHAR2(100) ,  --좋아요누른 아이디
    PBNO NUMBER PRIMARY KEY, --좋아요 눌려진 게시판 번호 
    USERIP VARCHAR2(50) --IP
);

COMMENT ON COLUMN PLIKE.USERID IS '좋아요누른아이디';
COMMENT ON COLUMN PLIKE.PBNO IS '좋아요눌려진게시판번호';
COMMENT ON COLUMN PLIKE.USERIP IS '사용자아이피'; 


CREATE TABLE P_LIKE (
    PBNO VARCHAR2(1000),
    LIKEY_N VARCHAR2(2) DEFAULT 'N' CHECK(LIKEY_N IN('N','Y')),
    LIKEID VARCHAR2(30),
    PLNO NUMBER PRIMARY KEY
);



-- 일자 : 2020.02.22
-- 이름 : 박주완
-- 내용 : 신고관련
CREATE TABLE REPORT (
   RNO NUMBER PRIMARY KEY,  -- 신고번호
   RPNO NUMBER, -- 게시물번호
   RPWRITER VARCHAR2(30) NOT NULL, -- 작성자
   REASON VARCHAR2(3000) DEFAULT 0, -- 정지사유
   RPDATE DATE DEFAULT SYSDATE, -- 신고일
   RELEASEDATE DATE DEFAULT SYSDATE -1, -- 정지해제일
   REPORTER VARCHAR2(30) NOT NULL, -- 신고자
   RPCOUNT NUMBER DEFAULT 0, -- 누적정지횟수
   RPSTATUS VARCHAR2(1) DEFAULT 'N' CHECK (RPSTATUS IN ('N','Y')) -- 정지상태
   );

COMMENT ON COLUMN REPORT.RNO IS '신고번호';
COMMENT ON COLUMN REPORT.RPNO IS '게시글번호';
COMMENT ON COLUMN REPORT.RPWRITER IS '게시글작성자';
COMMENT ON COLUMN REPORT.REASON IS '정지사유';
COMMENT ON COLUMN REPORT.RPDATE IS '신고일';
COMMENT ON COLUMN REPORT.RELEASEDATE IS '정지해제일';
COMMENT ON COLUMN REPORT.REPORTER IS '신고자';
COMMENT ON COLUMN REPORT.RPCOUNT IS '누적정지횟수';
COMMENT ON COLUMN REPORT.RPSTATUS IS '현재정지유무';                    

CREATE SEQUENCE SEQUENCE_RNO
INCREMENT BY 1;

CREATE SEQUENCE SEQUENCE_RNO_RPCOUNT
INCREMENT BY 1;


COMMIT;